<?php
require_once('fpdf/fpdf.php');
require_once('../config/config.php');
require_once('../config/db_connect.php');
	
class PDF extends FPDF{
  /**
  function Header(){
    $this->SetFont('Times','B',12);
    $this->Ln(0);
    $this->Cell(16,0.5, $this->Image('logo.jpg', $this->GetX(), $this->GetY(),2.9,2.9,0,0), 0, 0, 'L', false );
    $this->Cell(0.3,0.5,'',0,0,'J',0);
    //$this->Cell(1.4,0.5, $this->Image($gambar2, $this->GetX(), $this->GetY(),2.2,1.7,0,0),0, 0, 'R', false );
    $this->Ln(0);
    $this->Cell(21,0.8,'PEMERINTAH KABUPATEN INDRAMAYU',0,0,'C');
    $this->Ln(0.5);
    $this->Cell(21,0.8,'DINAS PENDIDIKAN',0,0,'C');
    $this->Ln(0.5);
    $this->Cell(21,0.8,'YAYASAN AL-ISLAM INDRAMAYU',0,0,'C');
	$this->Ln(0.5);
	$this->SetFont('Times','B',14);
    $this->Cell(21,0.8,'SEKOLAH DASAR ISLAM AL-JANNAH',0,0,'C');
	$this->Ln(0.5);
	$this->SetFont('Arial','B',8);
    $this->Cell(21,0.8,'Alamat Jl. Raya Gabuswetan No. 1 Gabuswetan Indramayu 45263 Telp. (0234)5508501',0,0,'C');
	$this->Ln(0.35);
    $this->Cell(21,0.8,'E-mail: sdi.aljannah@gmail.com Laman: https://sdi-aljannah.web.id',0,0,'C');
    $this->Ln(0.5);
	$this->SetLineWidth(0.09);
	$this->Line(1,4.2,20,4.2);
	$this->SetLineWidth(0);
	$this->Line(1,4.3,20,4.3);
	$this->Ln(0.5);
  }

  function Footer(){
   $this->SetY(-2,5);
   $this->Cell(0,0.7,'SD ISLAM AL-JANNAH GABUSWETAN KABUPATEN INDRAMAYU - Halaman : '. $this->PageNo(),'BTRL',0,'C');
  }
 **/
 }
 $id=$_GET['id'];
$sqls = "select * from sk where id_sk='$id'";
$querys = $connect->query($sqls);
$sk=$querys->fetch_assoc();
$idptk=$sk['ptk_id'];
$sqln = "select * from ptk where ptk_id='$idptk'";
$queryn = $connect->query($sqln);
$ptk=$queryn->fetch_assoc();

   $pdf = new PDF('P','cm',array(21.5,33));
   $pdf->AliasNbPages();
   $pdf->AddPage();
   $pdf->SetFont('Times','B',24);
    $pdf->Cell(16,0.5, $pdf->Image('logoyai.jpg', $pdf->GetX(), $pdf->GetY(),2.9,2.9,0,0), 0, 0, 'L', false );
    $pdf->Cell(0.3,0.5,'',0,0,'J',0);
	$pdf->Ln(0.2);
    //$pdf->Cell(1.4,0.5, $pdf->Image($gambar2, $pdf->GetX(), $pdf->GetY(),2.2,1.7,0,0),0, 0, 'R', false );
    $pdf->Cell(21,0.8,'YAYASAN AL-ISLAM',0,0,'C');
    $pdf->Ln(0.6);
	$pdf->SetFont('Times','B',12);
    $pdf->Cell(21,0.8,'Akte Notaris Suparto, S.H., M.Kn. No. 255 21 Juli 2016',0,0,'C');
    $pdf->Ln(0.7);
	$pdf->Cell(21,0.8,'SK. Kemenkumham RI Nomor AHU-0029604.AH.01.04 tgl. 22 Juli 2016',0,0,'C');
	$pdf->Ln(0.5);
	$pdf->SetFont('Times','B',10);
	$pdf->Cell(21,0.8,'Sekretariat: Jalan Raya Gabuswetan RT 9 RW 2 Desa Gabuswetan Kec. Gabuswetan Indramayu',0,0,'C');
    $pdf->Ln(0.5);
	$pdf->Cell(21,0.8,'Telp. 0234-5508501 Email: yayasan.alislam@gmail.com',0,0,'C');
    $pdf->SetFont('Times','B',12);
    $pdf->Ln(0.4);
	$pdf->SetLineWidth(0.09);
	$pdf->Line(1,4.2,20,4.2);
	$pdf->SetLineWidth(0);
	$pdf->Line(1,4.3,20,4.3);
	$pdf->Ln(1.3);
   $pdf->SetFont('Times','B','12');
   $pdf->Cell(0,0,'PETIKAN',0,0,'C');
   $pdf->Ln(0.5);
   $pdf->Cell(0,0,'KEPUTUSAN KETUA YAYASAN AL-ISLAM',0,0,'C');
   $pdf->Ln(0.5);
   $pdf->Cell(0,0,'NOMOR : '.$sk['no_sk'],0,0,'C');
   $pdf->Ln(0.7);
   $pdf->Cell(0,0,'TENTANG',0,0,'C');
   $pdf->Ln(0.5);
   $pdf->Cell(0,0,'PENGANGKATAN '.strtoupper($sk['jenis_ptk']).' TETAP YAYASAN',0,0,'C');
   $pdf->Ln(0.5);
   $pdf->Cell(0,0,'SEKOLAH DASAR ISLAM (SDI) AL-JANNAH GABUSWETAN',0,0,'C');
   $pdf->Ln(0.8);
   $pdf->SetFont('Times','','12');
   $pdf->Cell(4,0.5,'Menimbang',0,0,'L');
   $pdf->Cell(0.4,0.5,':',0,0,'L');
   $pdf->Cell(0.5,0.5,'a.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Bahwa untuk memenuhi kebutuhan '.$sk['jenis_ptk'].', maka perlu mengangkat '.$sk['jenis_ptk'].' pada Yayasan Al-Islam;',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'b.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Bahwa pengangkatan dan penempatan '.$sk['jenis_ptk'].' pada satuan pendidikan yang diselenggarakan oleh masyarakat didasarkan pada kesepakatan kerja bersama;',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'c.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Bahwa berdasarkan pertimbangan sebagaimana dimaksud pada butir a dan butir b di atas, maka perlu menetapkan Pengangkatan '.$sk['jenis_ptk'].' Tetap Yayasan Al-Islam.',0,'J',0);
   $pdf->Ln(0.2);
   $pdf->Cell(4,0.5,'Mengingat',0,0,'L');
   $pdf->Cell(0.4,0.5,':',0,0,'L');
   $pdf->Cell(0.5,0.5,'1.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Undang-undang Nomor 20 tahun 2003 tentang Sistem Pendidikan Nasional;',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'2.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Undang-undang Nomor 14 Tahun 2005 tentang Guru dan Dosen;',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'3.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Peraturan Pemerintah Nomor 74 Tahun 2008 tentang Guru;',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'4.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Peraturan Pemerintah Nomor 19 Tahun 2005 tentang Standar Nasional Pendidikan sebagaimana telah diubah menjadi Peraturan Pemerintah Nomor 32 Tahun 2013 tentang Perubahan atas Peraturan Pemerintah Nomor 19 Tahun 2005 tentang Standar Nasional Pendidikan;',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'5.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Peraturan Menteri Pendidikan Nasional Nomor 16 Tahun 2007 tentang Standar Kualifikasi Akademik dan Kompetensi Guru;',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'6.',0,0,'L');
   $pdf->MultiCell(14,0.5,'Anggaran Dasar dan Anggaran Rumah Tangga Yayasan Al-Islam yang tertuang dalam Akta Notaris No. 255 tanggal 21 Juli 2016.',0,'J',0);
   $pdf->Ln(0.2);
   $pdf->SetFont('Times','B','12');
   $pdf->MultiCell(19,0.5,'MEMUTUSKAN',0,'C',0);
   $pdf->Ln(0.2);
   $pdf->SetFont('Times','','12');
   $pdf->Cell(4,0.5,'Menetapkan',0,0,'L');
   $pdf->Cell(0.4,0.5,':',0,0,'L');
   $pdf->MultiCell(14.5,0.5,'Keputusan Ketua Yayasan Al-Islam tentang Pengangkatan '.$sk['jenis_ptk'].' Tetap Yayasan di Sekolah Dasar Islam Al-Jannah',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'PERTAMA',0,0,'L');
   $pdf->Cell(0.4,0.5,':',0,0,'L');
   $pdf->MultiCell(14.5,0.5,'Terhitung mulai tanggal '.TanggalIndo($sk['tanggal_sk']).' mengangkat :',0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'1.',0,0,'L');
   $pdf->Cell(4.5,0.5,'Nama',0,0,'L');
   $pdf->Cell(0.5,0.5,':',0,0,'L');
   $pdf->SetFont('Times','B','12');
   $pdf->MultiCell(10,0.5,strtoupper($ptk['nama']),0,'J',0);
   $pdf->Ln(0);
   $pdf->SetFont('Times','','12');
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'2.',0,0,'L');
   $pdf->Cell(4.5,0.5,'Tempat, Tanggal Lahir',0,0,'L');
   $pdf->Cell(0.5,0.5,':',0,0,'L');
   $pdf->MultiCell(10,0.5,$ptk['tempat_lahir'].', '.TanggalIndo($ptk['tanggal_lahir']),0,'J',0);
   $pdf->Ln(0);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->Cell(0.5,0.5,'3.',0,0,'L');
   $pdf->Cell(4.5,0.5,'Pendidikan Terakhir',0,0,'L');
   $pdf->Cell(0.5,0.5,':',0,0,'L');
   $pdf->MultiCell(10,0.5,$sk['pendidikan'],0,'J',0);
   $pdf->Ln(0.1);
   $pdf->Cell(4,0.5,'',0,0,'L');
   $pdf->Cell(0.4,0.5,'',0,0,'L');
   $pdf->MultiCell(14.5,0.5,'sebagai '.$sk['jenis_ptk'].' Tetap Yayasan Al-Islam untuk mengampu '.$sk['jabatan'].' pada Sekolah di bawah naungan Yayasan Al-Islam',0,'J',0);
   $pdf->Ln(0.2);
   $pdf->Cell(4,0.5,'KEDUA',0,0,'L');
   $pdf->Cell(0.4,0.5,':',0,0,'L');
   $pdf->MultiCell(14.5,0.5,'Kepada yang bersangkutan diberikan gaji dan tunjangan lain sesuai ketentuan Yayasan Al-Islam;',0,'J',0);
   $pdf->Ln(0.2);
   $pdf->Cell(4,0.5,'KETIGA',0,0,'L');
   $pdf->Cell(0.4,0.5,':',0,0,'L');
   $pdf->MultiCell(14.5,0.5,'Keputusan ini berlaku sejak tanggal ditetapkan, dengan ketentuan apabila dikemudian hari terdapat kekeliruan dalam keputusan ini akan dilakukan perbaikan sebagaimana mestinya.',0,'J',0);
   $pdf->Ln(0.5);
   $pdf->Cell(12);
   $pdf->Cell(2.5,0.5,'Ditetapkan di',0,0,'L');
   $pdf->Cell(0.4,0.5,':',0,0,'L');
   $pdf->Cell(4,0.5,'Gabuswetan',0,0,'L');
   $pdf->Ln(0.5);
   $pdf->Cell(12);
   $pdf->Cell(2.5,0.5,'Pada Tanggal',0,0,'L');
   $pdf->Cell(0.4,0.5,':',0,0,'L');
   $pdf->Cell(4,0.5,TanggalIndo($sk['tanggal_sk']),0,0,'L');
   $pdf->Ln(0.5);
   $pdf->Cell(12);
	$pdf->SetLineWidth(0.05);
	$pdf->Line(13.15,26.9,19,26.9);
	$pdf->Ln(0.2);
   $pdf->Cell(12);
   $pdf->Cell(6,0.5,'Yayasan AL-ISLAM',0,0,'C');
   $pdf->Ln(0.5);
   $pdf->Cell(12);
   $pdf->Cell(6,0.5,'Ketua,',0,0,'C');
   $pdf->Ln(2.6);
   $pdf->Cell(12);
   $pdf->SetFont('Times','BU','12');
   $pdf->Cell(6,0.5,$sk['pengangkat'],0,0,'C');
   
   
   $pdf->SetTitle("Surat Keterangan Kelakuan Baik");
   $pdf->SetAuthor("APINS");
   $pdf->SetCreator("Nandang");
   $pdf->SetKeywords("APINS");
   $pdf->SetSubject("APINS");

   $pdf->Output();
 ?>
